version: "3.5"
services:
  db:
    container_name: sky-user-manager-db
    hostname: sky-user-manager-db
    image: mysql:8.4
    volumes:
      - ./storage/db:/var/lib/mysql:rw
      - ./src/main/sql:/docker-entrypoint-initdb.d/:r
    environment:
      - MYSQL_DATABASE=db_sky_user_manager
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: on-failure
    networks:
      - sky-user-manager-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    container_name: sky-user-manager
    build:
      dockerfile: Dockerfile
    image: sky-user-manager:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sky-user-manager-network

networks:
  sky-user-manager-network:
    name: sky-user-manager-network
    driver: bridge
